### PR TITLE
Track 1102 - Add drag/drop sorting to the fixtable

### PR DESCRIPTION
**Pull request by sfanetti**
This is a really rudimentary way to add drag/drop sorting to the fixtable rows.  This is implemented only on rows now and its not intended to receive random drops and stuff.

reordering

### CODE REVIEW

**Comment by rbrcurtis** [comment]
Can you squash your commits into a single one with a sanitary comment? This is public after all.
Otherwise looks great.

**Comment by michaelmcauley** [comment]
Looks great, I just have a couple quibbles...

Firstly, I'd recommend changing cursor when hovering over draggable rows to provide an affordance that user can drag. I guess `move` is the conventional cursor here?

Second, I don't love the UX when dropping. Since only the row is highlighted, it's not obvious whether the row you're dragging is going to go _above_ or _below_ the row you're dropping on (until you learn the heuristic that it depends on which direction you've dragged from starting point). I know there's no straightforward way to do this, but maybe there's some way to be clever with using top or bottom border on hovered row to indicate where it will be dropped, or something else like that?

I have no problem approving as-is, but I'd definitely prefer something more usable in terms of it being clear where the row will be dropped without having to learn the rules of the system.

**Comment by sfanetti** [comment]
I agree Mike - ill play with it and give a better drop behavior to the user to better control before and after the drop target.  And i'll rebase the changes to be one clean commit as well.

**Comment by sfanetti** [comment]
Squashed into one branch and added visual cues to indicate into which location the drop will occur
editor-replace-alt

**Comment by michaelmcauley** [comment]
Looks great 👍

**Pull request merged**
